import { RiArrowDropRightLine, RiArrowDropLeftLine } from "react-icons/ri";
import Head from "next/head";
import TaskBar from "../components/Dashboard/TaskBar";
import AgentBar from "../components/Dashboard/AgentBar";
import { useEffect, useState } from "react";
import Gmap from "../components/Dashboard/Gmap";

const dashboard = () => {
  const [showTaskBar, setShowTaskBar] = useState(false);
  const [showAgentBar, setShowAgentBar] = useState(false);




  return (
    <div className="flex justify-between">
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Left Panel */}
      <div className="relative flex">
        {showTaskBar && (
          <div className="flex">
            <TaskBar className=""/>

          </div>
        )}
        
      </div>

      {/* Middle Panel */}
      <div className="relative flex w-full">
      <div className={(showTaskBar ? "hidden" : "block") }>
        <RiArrowDropRightLine
          className="absolute top-0 left-0 z-20 p-0 text-4xl bg-gray-300"
          onClick={() => setShowTaskBar(true)}
          />
          </div>
          <RiArrowDropLeftLine
              className="absolute top-0 left-0 z-10 p-0 text-4xl bg-gray-300"
              onClick={() => setShowTaskBar(false)}
            />
        <Gmap />
        <RiArrowDropRightLine
              className="absolute top-0 right-0 p-0 text-4xl bg-gray-300"
              onClick={() => setShowAgentBar(false)}
            />
        <div className={(showAgentBar ? "hidden" : "block")}>
        <RiArrowDropLeftLine
          className="absolute top-0 right-0 p-0 text-4xl bg-gray-300"
          onClick={() => setShowAgentBar(true)}
          />
          </div>
      </div>

      {/* Right Panel */}
      
      <div className="flex">
      
        {showAgentBar && (
          <div className="">
            <AgentBar />
          </div>
        )}
      </div>
    </div>
  );
};

export default dashboard;
