import Head from 'next/head';

export default function Home() {
  return (
    <div className="flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="text-5xl font-semibold">Index Page</h2>
    </div>
  )
}
